[env]
TERM = "xterm-256color"


[window]
startup_mode = "Maximized"
decorations = "Full"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold   = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 16.0
