[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
startup_mode = "Maximized"
decorations = "Full"

[font]
normal = { family = "CascadiaCode Nerd Font", style = "Regular" }
bold   = { family = "CascadiaCode Nerd Font", style = "Bold" }
italic = { family = "CascadiaCode Nerd Font", style = "Italic" }
size = 16.0
