# Disable the clock in the prompt
[time]
disabled = true

# Keep directory and git info visible (these are defaults, but explicit is better)
[directory]
truncation_length = 3
truncate_to_repo = false

[git_status]
disabled = false
# Use a direct porcelain query instead of upstream:track
detect_untracked_files = true
show_sync_count = true

[conda]
format = '[$symbol$environment](dimmed green) '
ignore_base = true           # hide when 'base' is active
disabled = false
